package com.ghz.bean.mg;

import java.util.Date;

public class BossList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_list.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_list.round
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer round;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_list.current_num
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer currentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_list.total_num
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer totalNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_list.start_date
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Date startDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_list.id
     *
     * @return the value of boss_list.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_list.id
     *
     * @param id the value for boss_list.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_list.round
     *
     * @return the value of boss_list.round
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getRound() {
        return round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_list.round
     *
     * @param round the value for boss_list.round
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setRound(Integer round) {
        this.round = round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_list.current_num
     *
     * @return the value of boss_list.current_num
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getCurrentNum() {
        return currentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_list.current_num
     *
     * @param currentNum the value for boss_list.current_num
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setCurrentNum(Integer currentNum) {
        this.currentNum = currentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_list.total_num
     *
     * @return the value of boss_list.total_num
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_list.total_num
     *
     * @param totalNum the value for boss_list.total_num
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_list.start_date
     *
     * @return the value of boss_list.start_date
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_list.start_date
     *
     * @param startDate the value for boss_list.start_date
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
}