package com.ghz.bean.mg;

public class Boss {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss.current_hp
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer currentHp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss.max_hp
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer maxHp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss.list_id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer listId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss.ordered
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer ordered;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss.id
     *
     * @return the value of boss.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss.id
     *
     * @param id the value for boss.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss.current_hp
     *
     * @return the value of boss.current_hp
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getCurrentHp() {
        return currentHp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss.current_hp
     *
     * @param currentHp the value for boss.current_hp
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setCurrentHp(Integer currentHp) {
        this.currentHp = currentHp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss.max_hp
     *
     * @return the value of boss.max_hp
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getMaxHp() {
        return maxHp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss.max_hp
     *
     * @param maxHp the value for boss.max_hp
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setMaxHp(Integer maxHp) {
        this.maxHp = maxHp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss.list_id
     *
     * @return the value of boss.list_id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss.list_id
     *
     * @param listId the value for boss.list_id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setListId(Integer listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss.ordered
     *
     * @return the value of boss.ordered
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getOrdered() {
        return ordered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss.ordered
     *
     * @param ordered the value for boss.ordered
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setOrdered(Integer ordered) {
        this.ordered = ordered;
    }
}