package com.ghz.bean.mg;

public class GhzData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ghz_data.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ghz_data.current_boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer currentBossList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ghz_data.id
     *
     * @return the value of ghz_data.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ghz_data.id
     *
     * @param id the value for ghz_data.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ghz_data.current_boss_list
     *
     * @return the value of ghz_data.current_boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getCurrentBossList() {
        return currentBossList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ghz_data.current_boss_list
     *
     * @param currentBossList the value for ghz_data.current_boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setCurrentBossList(Integer currentBossList) {
        this.currentBossList = currentBossList;
    }
}