package com.ghz.bean.mg;

import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.util.Date;

@ToString
public class KnifeData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_data.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_data.member_id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_data.damage
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer damage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_data.boss_id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer bossId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_data.round
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer round;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_data.date
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_data.id
     *
     * @return the value of knife_data.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_data.id
     *
     * @param id the value for knife_data.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_data.member_id
     *
     * @return the value of knife_data.member_id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_data.member_id
     *
     * @param memberId the value for knife_data.member_id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_data.damage
     *
     * @return the value of knife_data.damage
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getDamage() {
        return damage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_data.damage
     *
     * @param damage the value for knife_data.damage
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setDamage(Integer damage) {
        this.damage = damage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_data.boss_id
     *
     * @return the value of knife_data.boss_id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getBossId() {
        return bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_data.boss_id
     *
     * @param bossId the value for knife_data.boss_id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setBossId(Integer bossId) {
        this.bossId = bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_data.round
     *
     * @return the value of knife_data.round
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getRound() {
        return round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_data.round
     *
     * @param round the value for knife_data.round
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setRound(Integer round) {
        this.round = round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_data.date
     *
     * @return the value of knife_data.date
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_data.date
     *
     * @param date the value for knife_data.date
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }
}