package com.ghz.bean.mg;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.number_id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private String numberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.nick_name
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private String nickName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.number_id
     *
     * @return the value of member.number_id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public String getNumberId() {
        return numberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.number_id
     *
     * @param numberId the value for member.number_id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setNumberId(String numberId) {
        this.numberId = numberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.nick_name
     *
     * @return the value of member.nick_name
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.nick_name
     *
     * @param nickName the value for member.nick_name
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
}