package com.ghz.bean.mg;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ghz_user.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ghz_user.username
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ghz_user.password
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ghz_user.password_sha512
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private String passwordSha512;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ghz_user.nick_name
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    private String nickName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ghz_user.id
     *
     * @return the value of ghz_user.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ghz_user.id
     *
     * @param id the value for ghz_user.id
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ghz_user.username
     *
     * @return the value of ghz_user.username
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ghz_user.username
     *
     * @param username the value for ghz_user.username
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ghz_user.password
     *
     * @return the value of ghz_user.password
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ghz_user.password
     *
     * @param password the value for ghz_user.password
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ghz_user.password_sha512
     *
     * @return the value of ghz_user.password_sha512
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public String getPasswordSha512() {
        return passwordSha512;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ghz_user.password_sha512
     *
     * @param passwordSha512 the value for ghz_user.password_sha512
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setPasswordSha512(String passwordSha512) {
        this.passwordSha512 = passwordSha512;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ghz_user.nick_name
     *
     * @return the value of ghz_user.nick_name
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ghz_user.nick_name
     *
     * @param nickName the value for ghz_user.nick_name
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
}