
server:
#  port: 18080 #内置tomcat端口
  port: 80
  tomcat:
    uri-encoding: UTF-8 #URL字符编码
  servlet:
    session:
      timeout: 1440m #session生命周期
    encoding:
      force: true
      enabled: true
      charset: UTF-8

spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/ghz?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 7ujMko0admin123#
#    password: 123456
#    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapping/*.xml,classpath:/mapping/mg/*.xml
  type-aliases-package: com.cssc.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true
    cache-enabled: true
    aggressiveLazyLoading: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0