package com.ghz.bean.repository.mg;

import com.ghz.bean.mg.Boss;
import com.ghz.bean.mg.BossExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BossMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    long countByExample(BossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int deleteByExample(BossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int insert(Boss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int insertSelective(Boss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    List<Boss> selectByExample(BossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    Boss selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") Boss record, @Param("example") BossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int updateByExample(@Param("record") Boss record, @Param("example") BossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int updateByPrimaryKeySelective(Boss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int updateByPrimaryKey(Boss record);
}