package com.ghz.bean.repository.mg;

import com.ghz.bean.mg.BossList;
import com.ghz.bean.mg.BossListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BossListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    long countByExample(BossListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int deleteByExample(BossListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int insert(BossList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int insertSelective(BossList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    List<BossList> selectByExample(BossListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    BossList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") BossList record, @Param("example") BossListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int updateByExample(@Param("record") BossList record, @Param("example") BossListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int updateByPrimaryKeySelective(BossList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_list
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int updateByPrimaryKey(BossList record);
}