package com.ghz.bean.repository.mg;

import com.ghz.bean.mg.GhzData;
import com.ghz.bean.mg.GhzDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GhzDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghz_data
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    long countByExample(GhzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghz_data
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int deleteByExample(GhzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghz_data
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghz_data
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int insert(GhzData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghz_data
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int insertSelective(GhzData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghz_data
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    List<GhzData> selectByExample(GhzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghz_data
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    GhzData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghz_data
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") GhzData record, @Param("example") GhzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghz_data
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int updateByExample(@Param("record") GhzData record, @Param("example") GhzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghz_data
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int updateByPrimaryKeySelective(GhzData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghz_data
     *
     * @mbg.generated Thu May 21 11:12:11 CST 2020
     */
    int updateByPrimaryKey(GhzData record);
}